name: voila
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - jupyterlab
  - leafmap
  - maplibre
  - voila
  - voila_topbar
  - leafmap
  - geemap
  - mapwidget
  - geopandas
  - localtileserver
  - nodejs
